# Generated by Django 4.0 on 2024-05-02 16:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subject_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subject_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
